# Generated by Django 4.2.25 on 2025-10-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Electronics", "Electronics"),
                    ("Clothes", "Clothes"),
                    ("Books", "Books"),
                    ("Furniture", "Furniture"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
