# Generated by Django 4.2.25 on 2025-10-14 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_options_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Female",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Male",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_male", models.CharField(max_length=100)),
                (
                    "girls",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.female",
                    ),
                ),
            ],
        ),
    ]
